# Generated by Django 4.1.3 on 2024-04-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_menu_delete_preference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='nombre',
            new_name='title',
        ),
    ]
