# Generated by Django 4.1.3 on 2024-05-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_menu_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='nombre',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
