# Generated by Django 4.1.3 on 2024-05-22 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_menu_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='nombre',
        ),
    ]
