# Generated by Django 4.1.3 on 2024-05-22 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='calificacion',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
